# This is a basic workflow to help you get started with Actions

name: CI Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Get development tools
      run: sudo apt-get install gnat gprbuild libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev

    - name: Checkout SDLAda
      run: git clone https://github.com/Lucretia/sdlada.git

    - name: Build SDLAda
      run: |
        cd sdlada/build/gnat
        SDL_PLATFORM=linux SDL_MODE=release make
        SDL_PLATFORM=linux SDL_MODE=release make install
        cd
      
    # Runs a set of commands using the runners shell
    - name: Build Fixed Rate Pig
      run: gprbuild -v pig.gpr -aP /opt/share/gpr -k -largs -lsdl2 -lsdl2_ttf -lsdl2_image
